name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        with:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          release_name: "Release ${{ github.ref }}"
          draft: false
          prerelease: false

      - name: Set asset path and name
        id: set_asset
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            echo "::set-output name=asset_path::target/release/nvm.exe"
            echo "::set-output name=asset_name::nvm-windows.exe"
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            echo "::set-output name=asset_path::target/release/nvm"
            echo "::set-output name=asset_name::nvm-macos"
          else
            echo "::set-output name=asset_path::target/release/nvm"
            echo "::set-output name=asset_name::nvm-linux"
          fi

      - name: Upload Release Asset
        uses: actions/upload-release-asset@latest
        with:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.set_asset.outputs.asset_path }}
          asset_name: ${{ steps.set_asset.outputs.asset_name }}
          asset_content_type: application/octet-stream